name = "fitnessup"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[build]
command = "npm run build"

[[routes]]
pattern = "/*"
run = "" 

[vars]
NODE_ENV = "production"

[env.production]
vars = { NODE_ENV = "production" }